[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "-- TARGET: add your own CardAreas for joker evaluation"
position = 'before'
match_indent = true
payload = '''
if G.flace then table.insert(t, G.flace) end
'''

[[patches]]
[patches.pattern]
target = '=[SMODS partner "partner.lua"]'
pattern = "G.GAME.skip_partner = true"
position = 'after'
match_indent = true
payload = '''
if not G.GAME.cancel_flace then create_UIBox_your_collection_stolen() end
'''

[[patches]]
[patches.pattern]
target = '=[SMODS partner "partner.lua"]'
pattern = '''G.FUNCS.select_partner = function()
    G.FUNCS.exit_overlay_menu()'''
position = 'after'
match_indent = true
payload = '''
if not G.GAME.cancel_flace then create_UIBox_your_collection_stolen() end
'''